---
- name: Deploy Open WebUI
  hosts: node

  tasks:
  - name: Pull latest code from GitHub
    git:
      repo: https://github.com/ragan/open-webui-compose.git
      dest: ~/open-webui-compose
      version: main
      update: yes
    register: git_result

  - name: Stop existing containers
    command: docker-compose down
    args:
      chdir: ~/open-webui-compose
    when: git_result.changed

  - name: Start new containers
    command: docker-compose up -d
    args:
      chdir: ~/open-webui-compose
    when: git_result.changed

