[manager]
show_hidden = true

[opener]
edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
]

[open]
rules = [
	{ mime = "text/*", use = "edit" },
	{ mime = "application/json", use = "edit" },
	{ mime = "application/x-yaml", use = "edit" },
]

[flavor]
use = "rose-pine"
